name: 'Jest Coverage Comment Action'
description: 'Comments a PR with the coverage (jest)'
author: raulanatol
branding:
  color: green
  icon: message-circle
inputs:
  github-token:
    description: 'Github token'
    required: true
  jest-command:
    description: 'The jest command'
    required: false
    default: 'npx jest --coverage'
  only-changes:
    description: 'Add parameter to show the coverage only for the changed files'
    required: false
    default: 'true'
  working-directory:
    description: 'Specify a directory where npm command has to be executed'
    required: false
    default: ''
  delete-previous:
    description: 'Delete previous comments before adding a new one'
    required: false
    default: 'true'
  use-existing-reports:
    description: 'Use existing coverage report fi exists, and do not run the tests'
    required: false
    default: 'false'
  measures-server-host:
    description: 'Host + endpoint to retreive (GET) and set (POST) measures. If unset, functionality is disabled. Example: https://49f0-81-61-118-50.eu.ngrok.io/v1/testing/report/measures'
    required: false
  measures-server-auth-header-parameter:
    description: 'Header field for sending the auth-token to identify aginst the measures server'
    required: false
    default: 'bearer'
  measures-server-auth-token:
    description: 'Key to identify against the measures server'
    required: false
  measures-server-cors-origin:
    description: 'In case of having CORS enabled in measures server'
    required: false
  measures-server-repository:
    description: 'Repository name to identify in the measures server. Example: backend, front, app, ...'
    required: false
  measures-server-main-branch:
    description: 'Identifies the branch from whom the measures are sent to the host. This will be the branch against the others will compare.'
    required: false
    default: 'main'
runs:
  using: 'node12'
  main: 'dist/index.js'
